# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'Board' do

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SDWebImage'

pod 'TextFieldEffects'
pod 'JTSImageViewController'
pod 'CRToast'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

pod 'MJRefresh'
pod 'DZNEmptyDataSet'

pod 'WYMaterialButton'
pod 'RESideMenu'
pod 'SnapKit'

pod 'Venmo-iOS-SDK'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'


end

target 'BoardTests' do

end

target 'BoardUITests' do

end

